---
azure_devops_org_url: "https://dev.azure.com/anoopkum"
azure_devops_project: "Azure-platform-engineering"
azure_devops_pool_name: "self-hosted-linux"
agent_version: "3.240.1"
agent_install_dir: /opt/azure-agent

argocd_version: "v2.11.0"
argocd_cli_install_path: /usr/local/bin/argocd

node_packages:
  - curl
  - git
  - jq
  - unzip
  - apt-transport-https
  - ca-certificates
  - python3-pip
  - python3-venv
